/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author madhu
 */

import java.io.*;
import com.sun.speech.freetts.*;
import edu.cmu.sphinx.api.Configuration;
import edu.cmu.sphinx.api.LiveSpeechRecognizer;
import edu.cmu.sphinx.api.SpeechResult;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Txttspe extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static Configuration configuration;
    static LiveSpeechRecognizer recognize;
    int i=0,x=0,count=0;
    public Txttspe() throws FileNotFoundException, IOException {
        initComponents();
        configuration = new Configuration();
        configuration.setAcousticModelPath("resource:/edu/cmu/sphinx/models/en-us/en-us");
         configuration.setDictionaryPath("2248.dic");
         configuration.setLanguageModelPath("2248.lm");
         recognize= new LiveSpeechRecognizer(configuration);
         
    }
   
    
    
    public void llgg(){
        try {
                start();
        while (i==0) {            
             x=check();
            if(x==1){
                jTextField1.setText("A");
                break;
                
                
                
            }else if(x==2){
                jTextField1.setText("D");
                start();
                
            }
        }
            } catch (Exception ex) {
               
            }
    }
    
    
    public static int check() throws IOException{

         
         
         
         recognize.startRecognition(true);
         int x=0;
         SpeechResult result;
         while ((result=recognize.getResult()) != null) {            
            String command=result.getHypothesis();
            
            
             if (command.equalsIgnoreCase("A")) {
                 x=1;
                 //new Audio_Player().setVisible(true);
                 
                recognize.stopRecognition();
                
                 
                break;
              //   ProcessBuilder pb = new ProcessBuilder("Notepad.exe", "myfile.txt");
                // pb.start();
             }else if (command.equalsIgnoreCase("D")) {
                 x=4;
                 recognize.stopRecognition();
                 
                 break;
                
             }
             
             
            
        }
         return x;
         
        }
    
    public static final String VOICENAME="kevin16";   
    public static void start() throws FileNotFoundException, IOException{
        String go="",pl="";
        int count=0;
        Voice voice;
        VoiceManager vm= VoiceManager.getInstance();
        voice= vm.getVoice(VOICENAME);
        
        voice.allocate();
        FileReader reader=new FileReader("ivrstart.txt");
        int character;
 
            while ((character = reader.read()) != -1) {
                go=go+(char) character;
            }
            reader.close();
        int i=0;
        for (int j = 0; j < go.length(); j++) {
            if(go.charAt(j)=='.'){
                count++;
            }
        }
        for (int j = 0; j < count; j++) {
            
        
            for (; i < go.length(); i++) {

                pl=pl+go.charAt(i);
                if(go.charAt(i)=='.'){
                    i++;
                    break;
                }
            }
            
            try {
                voice.speak(pl);
                Thread.sleep(500);
            } catch (Exception e) {
            }
            pl="";
        }
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        llgg();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        llgg();
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        JOptionPane.showMessageDialog(null, "dfishfsh");
    }//GEN-LAST:event_jTextField1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Txttspe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Txttspe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Txttspe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Txttspe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Txttspe().setVisible(true);
                   
                    
                } catch (IOException ex) {
                    Logger.getLogger(Txttspe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
